on: release
name: Build
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: GOOS=linux GOARCH=amd64 go build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: GOOS=windows GOARCH=amd64 go build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: benchmark.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: GOOS=darwin GOARCH=amd64 go build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
